# Generated by Django 5.0 on 2024-08-06 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_voo', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1)])),
                ('origem', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('destino', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('partida', models.DateTimeField()),
                ('chegada', models.DateTimeField()),
                ('assentos_disp', models.IntegerField()),
                ('preco', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('companhia', models.CharField(choices=[('GOL', 'Gol'), ('LAT', 'Latam'), ('AZU', 'Azul'), ('AAI', 'American Airlines'), ('QAN', 'Qantas')], max_length=15)),
                ('duracao_voo', models.DurationField()),
                ('status', models.CharField(choices=[('CAN', 'Cancelado'), ('DEL', 'Atrasado'), ('ON', 'No horário')], max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10)])),
                ('identidade', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(4)])),
                ('Nacionalidade', models.CharField(choices=[('ARG', 'Argentina'), ('BRA', 'Brasileira'), ('FRA', 'Francesa'), ('URU', 'Uruguaia')], max_length=15)),
                ('passaporte', models.CharField(max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(20)])),
                ('vencimento_passaporte', models.DateField()),
                ('endereco', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(50)])),
                ('voo', models.ManyToManyField(to='app.voo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
