# Generated by Django 4.1.13 on 2024-08-06 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_passageiro_endereco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passageiro',
            old_name='Nacionalidade',
            new_name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='passageiro',
            name='voo',
        ),
        migrations.AddField(
            model_name='voo',
            name='passageiro',
            field=models.ManyToManyField(blank=True, null=True, to='app.passageiro'),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='cod',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='voo',
            name='assentos_disp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='voo',
            name='cod_voo',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
