# Generated by Django 4.1.13 on 2024-08-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_nacionalidade_passageiro_nacionalidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='passageiro',
            field=models.ManyToManyField(blank=True, to='app.passageiro'),
        ),
    ]
